#!/usr/bin/env python3
# cfindent -- pretty-print map and player files with indentation
import sys

starts = {'checksum', 'arch', 'msg'}
ends = {'endplst', 'end', 'endmsg'}

def indent(file):
    level = 0
    for l in file.read().splitlines():
        first = l.split(' ')[0]
        if first in ends:
            level -= 1
        print('\t'*level + l)
        if first in starts:
            if first == 'checksum':
                level = 0
            level += 1

def main():
    indent(sys.stdin)

if __name__ == '__main__':
    main()
